# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QRouting
                                 A QGIS plugin
 Routing from A to B
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-12
        copyright            : (C) 2021 by Christian Beiwinkel
        email                : christian@gis-ops.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QRouting class from file QRouting.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qrouting import QRouting
    return QRouting(iface)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ICON_DIR = os.path.join(BASE_DIR, "icons")
