# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrouting/ui/raw/config_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_dialogue(object):
    def setupUi(self, settings_dialogue):
        settings_dialogue.setObjectName("settings_dialogue")
        settings_dialogue.resize(404, 212)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(settings_dialogue)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.costing_group = QgsCollapsibleGroupBox(settings_dialogue)
        self.costing_group.setCheckable(True)
        self.costing_group.setChecked(False)
        self.costing_group.setCollapsed(False)
        self.costing_group.setObjectName("costing_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.costing_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.costing_group)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.pedestrian = QtWidgets.QWidget()
        self.pedestrian.setObjectName("pedestrian")
        self.tabWidget.addTab(self.pedestrian, "")
        self.motorbike = QtWidgets.QWidget()
        self.motorbike.setObjectName("motorbike")
        self.tabWidget.addTab(self.motorbike, "")
        self.bicycle = QtWidgets.QWidget()
        self.bicycle.setObjectName("bicycle")
        self.tabWidget.addTab(self.bicycle, "")
        self.car = QtWidgets.QWidget()
        self.car.setObjectName("car")
        self.tabWidget.addTab(self.car, "")
        self.bus = QtWidgets.QWidget()
        self.bus.setObjectName("bus")
        self.tabWidget.addTab(self.bus, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.costing_group)
        self.avoid_group = QgsCollapsibleGroupBox(settings_dialogue)
        self.avoid_group.setEnabled(True)
        self.avoid_group.setFlat(False)
        self.avoid_group.setCheckable(True)
        self.avoid_group.setCollapsed(False)
        self.avoid_group.setObjectName("avoid_group")
        self.avoid_layer_dropdown = QgsMapLayerComboBox(self.avoid_group)
        self.avoid_layer_dropdown.setGeometry(QtCore.QRect(80, 30, 160, 32))
        self.avoid_layer_dropdown.setObjectName("avoid_layer_dropdown")
        self.verticalLayout.addWidget(self.avoid_group)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(settings_dialogue)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(settings_dialogue)
        self.tabWidget.setCurrentIndex(4)
        self.buttonBox.accepted.connect(settings_dialogue.accept)
        self.buttonBox.rejected.connect(settings_dialogue.reject)
        QtCore.QMetaObject.connectSlotsByName(settings_dialogue)

    def retranslateUi(self, settings_dialogue):
        _translate = QtCore.QCoreApplication.translate
        settings_dialogue.setWindowTitle(_translate("settings_dialogue", "Dialog"))
        self.costing_group.setTitle(_translate("settings_dialogue", "Costing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pedestrian), _translate("settings_dialogue", "Pedestrian"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.motorbike), _translate("settings_dialogue", "Motorbike"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bicycle), _translate("settings_dialogue", "Bicycle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.car), _translate("settings_dialogue", "Car"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bus), _translate("settings_dialogue", "Bus"))
        self.avoid_group.setTitle(_translate("settings_dialogue", "Avoid locations"))
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsmaplayercombobox import QgsMapLayerComboBox
