# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrouting/ui/raw/layer_select_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_layer(object):
    def setupUi(self, select_layer):
        select_layer.setObjectName("select_layer")
        select_layer.resize(315, 78)
        self.gridLayout = QtWidgets.QGridLayout(select_layer)
        self.gridLayout.setObjectName("gridLayout")
        self.mMapLayerComboBox = QgsMapLayerComboBox(select_layer)
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.gridLayout.addWidget(self.mMapLayerComboBox, 0, 0, 1, 1)

        self.retranslateUi(select_layer)
        QtCore.QMetaObject.connectSlotsByName(select_layer)

    def retranslateUi(self, select_layer):
        _translate = QtCore.QCoreApplication.translate
        select_layer.setWindowTitle(_translate("select_layer", "Form"))
from qgsmaplayercombobox import QgsMapLayerComboBox
