# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrouting/ui/raw/profile_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileWidget(object):
    def setupUi(self, ProfileWidget):
        ProfileWidget.setObjectName("ProfileWidget")
        ProfileWidget.resize(318, 68)
        self.gridLayout = QtWidgets.QGridLayout(ProfileWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ProfileWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.profile_ped = QtWidgets.QToolButton(ProfileWidget)
        self.profile_ped.setCheckable(True)
        self.profile_ped.setChecked(True)
        self.profile_ped.setObjectName("profile_ped")
        self.profile_buttons = QtWidgets.QButtonGroup(ProfileWidget)
        self.profile_buttons.setObjectName("profile_buttons")
        self.profile_buttons.addButton(self.profile_ped)
        self.horizontalLayout.addWidget(self.profile_ped)
        self.profile_mbike = QtWidgets.QToolButton(ProfileWidget)
        self.profile_mbike.setCheckable(True)
        self.profile_mbike.setObjectName("profile_mbike")
        self.profile_buttons.addButton(self.profile_mbike)
        self.horizontalLayout.addWidget(self.profile_mbike)
        self.profile_bike = QtWidgets.QToolButton(ProfileWidget)
        self.profile_bike.setCheckable(True)
        self.profile_bike.setObjectName("profile_bike")
        self.profile_buttons.addButton(self.profile_bike)
        self.horizontalLayout.addWidget(self.profile_bike)
        self.profile_car = QtWidgets.QToolButton(ProfileWidget)
        self.profile_car.setCheckable(True)
        self.profile_car.setObjectName("profile_car")
        self.profile_buttons.addButton(self.profile_car)
        self.horizontalLayout.addWidget(self.profile_car)
        self.profile_bus = QtWidgets.QToolButton(ProfileWidget)
        self.profile_bus.setCheckable(True)
        self.profile_bus.setObjectName("profile_bus")
        self.profile_buttons.addButton(self.profile_bus)
        self.horizontalLayout.addWidget(self.profile_bus)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.toolButton_6 = QtWidgets.QToolButton(ProfileWidget)
        icon = QtGui.QIcon.fromTheme(":images/themes/default/console/iconProcessingConsole.svg")
        self.toolButton_6.setIcon(icon)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout.addWidget(self.toolButton_6)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(ProfileWidget)
        QtCore.QMetaObject.connectSlotsByName(ProfileWidget)

    def retranslateUi(self, ProfileWidget):
        _translate = QtCore.QCoreApplication.translate
        ProfileWidget.setWindowTitle(_translate("ProfileWidget", "Form"))
        self.label.setText(_translate("ProfileWidget", "Profile"))
        self.profile_ped.setText(_translate("ProfileWidget", "..."))
        self.profile_mbike.setText(_translate("ProfileWidget", "..."))
        self.profile_bike.setText(_translate("ProfileWidget", "..."))
        self.profile_car.setText(_translate("ProfileWidget", "..."))
        self.profile_bus.setWhatsThis(_translate("ProfileWidget", "Transit"))
        self.profile_bus.setText(_translate("ProfileWidget", "..."))
        self.toolButton_6.setToolTip(_translate("ProfileWidget", "Profile settings"))
        self.toolButton_6.setText(_translate("ProfileWidget", "..."))
