# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrouting/ui/raw/qrouting_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QRoutingDialogBase(object):
    def setupUi(self, QRoutingDialogBase):
        QRoutingDialogBase.setObjectName("QRoutingDialogBase")
        QRoutingDialogBase.resize(400, 190)
        self.gridLayout = QtWidgets.QGridLayout(QRoutingDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.button_box = QtWidgets.QDialogButtonBox(QRoutingDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 3, 0, 1, 1)
        self.to_xy = QgsFilterLineEdit(QRoutingDialogBase)
        self.to_xy.setProperty("qgisRelation", "")
        self.to_xy.setObjectName("to_xy")
        self.gridLayout.addWidget(self.to_xy, 1, 0, 1, 1)
        self.from_xy = QgsFilterLineEdit(QRoutingDialogBase)
        self.from_xy.setProperty("qgisRelation", "")
        self.from_xy.setObjectName("from_xy")
        self.gridLayout.addWidget(self.from_xy, 0, 0, 1, 1)
        self.from_map_button = QtWidgets.QToolButton(QRoutingDialogBase)
        self.from_map_button.setObjectName("from_map_button")
        self.gridLayout.addWidget(self.from_map_button, 0, 1, 1, 1)
        self.to_map_button = QtWidgets.QToolButton(QRoutingDialogBase)
        self.to_map_button.setObjectName("to_map_button")
        self.gridLayout.addWidget(self.to_map_button, 1, 1, 1, 1)
        self.crs_input = QgsProjectionSelectionWidget(QRoutingDialogBase)
        self.crs_input.setObjectName("crs_input")
        self.gridLayout.addWidget(self.crs_input, 2, 0, 1, 2)

        self.retranslateUi(QRoutingDialogBase)
        self.button_box.accepted.connect(QRoutingDialogBase.accept)
        self.button_box.rejected.connect(QRoutingDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(QRoutingDialogBase)

    def retranslateUi(self, QRoutingDialogBase):
        _translate = QtCore.QCoreApplication.translate
        QRoutingDialogBase.setWindowTitle(_translate("QRoutingDialogBase", "QRouting"))
        self.to_xy.setPlaceholderText(_translate("QRoutingDialogBase", "To... (lat, lon)"))
        self.from_xy.setPlaceholderText(_translate("QRoutingDialogBase", "From... (lat, lon)"))
        self.from_map_button.setText(_translate("QRoutingDialogBase", "..."))
        self.to_map_button.setText(_translate("QRoutingDialogBase", "..."))
from qgsfilterlineedit import QgsFilterLineEdit
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
