# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrouting/ui/raw/qrouting_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .waypoint_widget_ui import Ui_WaypointWidget
from .profile_widget_ui import Ui_ProfileWidget

from ..util.resources import _locate_resource
from .. import BASE_DIR

class Ui_QRoutingDialogBase(object):
    def setupUi(self, QRoutingDialogBase):
        QRoutingDialogBase.setObjectName("QRoutingDialogBase")
        QRoutingDialogBase.resize(292, 400)
        self.gridLayout = QtWidgets.QGridLayout(QRoutingDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(QRoutingDialogBase)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.provider_label = QtWidgets.QLabel(self.widget)
        self.provider_label.setObjectName("provider_label")
        self.gridLayout_3.addWidget(self.provider_label, 0, 0, 1, 1)
        self.method_label = QtWidgets.QLabel(self.widget)
        self.method_label.setObjectName("method_label")
        self.gridLayout_3.addWidget(self.method_label, 1, 0, 1, 1)
        self.provider = QtWidgets.QComboBox(self.widget)
        self.provider.setObjectName("provider")
        self.provider.addItem("")
        self.provider.addItem("")
        self.gridLayout_3.addWidget(self.provider, 0, 1, 1, 2)
        self.method = QtWidgets.QComboBox(self.widget)
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.gridLayout_3.addWidget(self.method, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        # Profile stuff
        self.profile_widget = Ui_ProfileWidget()
        self.p_widget = QtWidgets.QWidget()
        self.profile_widget.setupUi(self.p_widget)
        self.gridLayout.addWidget(self.p_widget)
        self.profile_buttons = [
            self.profile_widget.profile_bike,
            self.profile_widget.profile_mbike,
            self.profile_widget.profile_bus,
            self.profile_widget.profile_ped,
            self.profile_widget.profile_car,
        ]

        # Waypoint stuff
        self.waypoint_widget = Ui_WaypointWidget()
        self.w_widget = QtWidgets.QWidget()
        self.waypoint_widget.setupUi(self.w_widget)
        self.gridLayout.addWidget(self.w_widget)
        self.waypoint_widget.coord_table.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)

        self.button_box = QtWidgets.QDialogButtonBox(QRoutingDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 5, 0, 1, 1)

        self.retranslateUi(QRoutingDialogBase)
        self.button_box.accepted.connect(QRoutingDialogBase.accept)
        self.button_box.rejected.connect(QRoutingDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(QRoutingDialogBase)

    def retranslateUi(self, QRoutingDialogBase):
        _translate = QtCore.QCoreApplication.translate
        QRoutingDialogBase.setWindowTitle(_translate("QRoutingDialogBase", "QRouting"))
        self.provider_label.setText(_translate("QRoutingDialogBase", "Provider"))
        self.method_label.setText(_translate("QRoutingDialogBase", "Method"))
        self.provider.setItemText(0, _translate("QRoutingDialogBase", "Valhalla"))
        self.provider.setItemText(1, _translate("QRoutingDialogBase", "OSRM"))
        self.method.setItemText(0, _translate("QRoutingDialogBase", "http"))
        self.method.setItemText(1, _translate("QRoutingDialogBase", "bindings"))

